"""empty message

Revision ID: 5106265d36bb
Revises: 998aa46eb9e0
Create Date: 2017-04-30 18:32:20.139701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5106265d36bb'
down_revision = '998aa46eb9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_type', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_files_file_type'), 'files', ['file_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_file_type'), table_name='files')
    op.drop_column('files', 'file_type')
    # ### end Alembic commands ###
