"""empty message

Revision ID: 998aa46eb9e0
Revises: 35405a9f16c4
Create Date: 2017-04-29 11:54:14.505960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998aa46eb9e0'
down_revision = '35405a9f16c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('file', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_analyses_file'), 'analyses', ['file'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_file'), table_name='analyses')
    op.drop_column('analyses', 'file')
    # ### end Alembic commands ###
