"""empty message

Revision ID: af4f04995bd7
Revises: 2e355040696b
Create Date: 2017-04-21 08:53:06.408212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4f04995bd7'
down_revision = '2e355040696b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_file', table_name='files')
    op.create_index(op.f('ix_files_file'), 'files', ['file'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_file'), table_name='files')
    op.create_index('ix_files_file', 'files', ['file'], unique=True)
    # ### end Alembic commands ###
